// <auto-generated />
using System;
using CourseworkApp.Database.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CourseworkApp.Database.Migrations
{
    [DbContext(typeof(WeatherDbContext))]
    [Migration("20250501141515_AddWeatherTable2")]
    partial class AddWeatherTable2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CourseworkApp.Database.Models.WeatherSensor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Relative_Humidity_2m")
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Temperature_2m")
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Wind_Direction_10m")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("Wind_Speed_10m")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.ToTable("weather");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EndDate = new DateTime(2025, 4, 29, 15, 15, 15, 588, DateTimeKind.Local).AddTicks(4018),
                            Name = "Default Sensor",
                            Relative_Humidity_2m = 65.0m,
                            StartDate = new DateTime(2025, 4, 28, 15, 15, 15, 588, DateTimeKind.Local).AddTicks(4016),
                            Temperature_2m = 18.5m,
                            Time = new DateTime(2025, 4, 28, 15, 15, 15, 588, DateTimeKind.Local).AddTicks(3953),
                            Wind_Direction_10m = 45.0m,
                            Wind_Speed_10m = 12.3m
                        },
                        new
                        {
                            Id = 2,
                            EndDate = new DateTime(2025, 4, 30, 15, 15, 15, 588, DateTimeKind.Local).AddTicks(4030),
                            Name = "Backup Sensor",
                            Relative_Humidity_2m = 70.0m,
                            StartDate = new DateTime(2025, 4, 29, 15, 15, 15, 588, DateTimeKind.Local).AddTicks(4028),
                            Temperature_2m = 20.1m,
                            Time = new DateTime(2025, 4, 29, 15, 15, 15, 588, DateTimeKind.Local).AddTicks(4022),
                            Wind_Direction_10m = 90.0m,
                            Wind_Speed_10m = 15.0m
                        },
                        new
                        {
                            Id = 3,
                            EndDate = new DateTime(2025, 4, 21, 15, 15, 15, 588, DateTimeKind.Local).AddTicks(4039),
                            Name = "Default Sensor",
                            Relative_Humidity_2m = 64.0m,
                            StartDate = new DateTime(2025, 4, 26, 15, 15, 15, 588, DateTimeKind.Local).AddTicks(4038),
                            Temperature_2m = 11.5m,
                            Time = new DateTime(2025, 4, 28, 15, 15, 15, 588, DateTimeKind.Local).AddTicks(4033),
                            Wind_Direction_10m = 44.0m,
                            Wind_Speed_10m = 11.1m
                        },
                        new
                        {
                            Id = 4,
                            EndDate = new DateTime(2025, 4, 29, 15, 15, 15, 588, DateTimeKind.Local).AddTicks(4047),
                            Name = "Default Sensor",
                            Relative_Humidity_2m = 65.0m,
                            StartDate = new DateTime(2025, 4, 28, 15, 15, 15, 588, DateTimeKind.Local).AddTicks(4045),
                            Temperature_2m = 15.5m,
                            Time = new DateTime(2025, 4, 28, 15, 15, 15, 588, DateTimeKind.Local).AddTicks(4041),
                            Wind_Direction_10m = 47.0m,
                            Wind_Speed_10m = 10.3m
                        },
                        new
                        {
                            Id = 5,
                            EndDate = new DateTime(2025, 4, 30, 15, 15, 15, 588, DateTimeKind.Local).AddTicks(4053),
                            Name = "Default Sensor",
                            Relative_Humidity_2m = 60.0m,
                            StartDate = new DateTime(2025, 4, 30, 15, 15, 15, 588, DateTimeKind.Local).AddTicks(4052),
                            Temperature_2m = 17.5m,
                            Time = new DateTime(2025, 4, 24, 15, 15, 15, 588, DateTimeKind.Local).AddTicks(4049),
                            Wind_Direction_10m = 45.0m,
                            Wind_Speed_10m = 10.3m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
